import type { IpcChannel, IpcStreamChannel } from '@spark/protocol'

export const CANVAS_INVOKE_CHANNELS = [
  // Canvas workspace, persistence, media tasks, and Agent bridge.
  'canvas:asset:copy-to-project',
  'canvas:asset:download',
  'canvas:asset:download-batch',
  'canvas:asset:write-data-url',
  'canvas:agent:open-workspace',
  'canvas:agent:configuration',
  'canvas:agent:session:answer-question',
  'canvas:agent:session:cancel',
  'canvas:agent:session:create',
  'canvas:agent:session:get-history',
  'canvas:agent:session:list',
  'canvas:agent:session:submit-turn',
  'canvas:agent:session:update',
  'canvas:host-attach',
  'canvas:host-detach',
  'canvas:media-capabilities:list',
  'canvas:media-models:describe',
  'canvas:media-models:list',
  'canvas:media:prune-model-params',
  'canvas:media:prune-model-params-by-inline-manifest',
  'canvas:project:cleanup-orphans',
  'canvas:project:default-root',
  'canvas:project:delete',
  'canvas:project:ensure-directory',
  'canvas:project:export-package',
  'canvas:project:import-package',
  'canvas:project:list',
  'canvas:project:migrate-assets',
  'canvas:project:update-cover',
  'canvas:snapshot:load',
  'canvas:snapshot:save',
  'canvas:task:cancel-media',
  'canvas:task:create-media',
  'canvas:task:generate-text',
  'canvas:tool-ack',
  'canvas:tool-result',
  'canvas:window:close-confirmed',
  'canvas:window:open',

  // Shared Spark account, upload, billing, and managed-model infrastructure.
  'auth:bind-status',
  'auth:bootstrap',
  'auth:captcha',
  'auth:change-password',
  'auth:client-config',
  'auth:get-base-url',
  'auth:login',
  'auth:login-sms',
  'auth:logout',
  'auth:me',
  'auth:refresh',
  'auth:register',
  'auth:send-code',
  'auth:send-sms',
  'auth:set-base-url',
  'auth:update-me',
  'auth:upload-avatar',
  'auth:upload-file',
  'auth:wechat-bind-email',
  'auth:wechat-bind-email-send-code',
  'auth:wechat-poll',
  'auth:wechat-qr',
  'platform-model:bootstrap',
  'platform-model:continue-on-this-device',
  'platform-model:get-plans',
  'platform-model:get-purchase-links',
  'platform-model:get-status',
  'platform-model:get-subscription',
  'platform-model:get-usage',
  'platform-model:open-purchase-link',
  'platform-model:pay',
  'platform-model:redeem',
  'platform-model:update-model-preferences',

  // BYOK provider and routing-model configuration used by the Canvas shell.
  'provider:create',
  'provider:delete',
  'provider:export',
  'provider:export-to-file',
  'provider:fetch-models',
  'provider:files:delete',
  'provider:files:get',
  'provider:files:list',
  'provider:files:upload',
  'provider:get-api-key',
  'provider:health-check',
  'provider:import',
  'provider:import-from-file',
  'provider:list',
  'provider:test-connection',
  'provider:update',
  'model:create',
  'model:delete',
  'model:list',
  'model:update',

  // Native shell, files, video workbench, settings, and updates.
  'app:get-info',
  'app:open-data-dir',
  'dialog:open-directory',
  'dialog:open-file',
  'ffmpeg:install',
  'ffmpeg:status',
  'file:open',
  'file:read-text',
  'file:reveal',
  'file:save-image',
  'file:save-canvas-annotation',
  'file:save-pasted-image',
  'file:stat-kind',
  'settings:get',
  'settings:set',
  'tool:open-folder',
  'update:check',
  'update:download',
  'update:get-status',
  'update:install-restart',
  'video:probe',
  'video:process',
  'window:close',
  'window:is-maximized',
  'window:maximize',
  'window:minimize',
  'window:set-zoom',
] as const satisfies readonly IpcChannel[]

export const CANVAS_STREAM_CHANNELS = [
  'stream:auth:session-expired',
  'stream:auth:state-changed',
  'stream:canvas-window:close-request',
  'stream:canvas:media-task',
  'stream:canvas:text-task',
  'stream:canvas:tool-call',
  'stream:config:changed',
  'stream:ffmpeg:install-progress',
  'stream:ffmpeg:status',
  'stream:session:agent-event',
  'stream:session:renamed',
  'stream:update:status',
  'stream:video:process-progress',
] as const satisfies readonly IpcStreamChannel[]

const canvasInvokeChannelSet: ReadonlySet<string> = new Set(CANVAS_INVOKE_CHANNELS)
const canvasStreamChannelSet: ReadonlySet<string> = new Set(CANVAS_STREAM_CHANNELS)

export function isCanvasInvokeChannelAllowed(channel: string): channel is IpcChannel {
  return canvasInvokeChannelSet.has(channel)
}

export function isCanvasStreamChannelAllowed(channel: string): channel is IpcStreamChannel {
  return canvasStreamChannelSet.has(channel)
}
